//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.FrontEnd.LibreriaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOEditorialCuerpo", Namespace="http://schemas.datacontract.org/2004/07/Libreria.Entidades.WCF.Editorial")]
    [System.SerializableAttribute()]
    public partial class DTOEditorialCuerpo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SedeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeField, value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOResultado", Namespace="http://schemas.datacontract.org/2004/07/Libreria.Entidades.WCF")]
    [System.SerializableAttribute()]
    public partial class DTOResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Libreria.FrontEnd.LibreriaService.EnumsCodigoRespuesta CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDePilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Libreria.FrontEnd.LibreriaService.EnumsCodigoRespuesta Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDePila {
            get {
                return this.ErrorDePilaField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDePilaField, value) != true)) {
                    this.ErrorDePilaField = value;
                    this.RaisePropertyChanged("ErrorDePila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.CodigoRespuesta", Namespace="http://schemas.datacontract.org/2004/07/Libreria.Entidades")]
    public enum EnumsCodigoRespuesta : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadRequest = 400,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unauthorized = 401,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 404,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidStatus = 406,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestTimeout = 408,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalServiceError = 500,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotImplemented = 501,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOLibroCuerpo", Namespace="http://schemas.datacontract.org/2004/07/Libreria.Entidades.WCF.Libro")]
    [System.SerializableAttribute()]
    public partial class DTOLibroCuerpo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EditorialesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NpaginasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SinopsisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EditorialesId {
            get {
                return this.EditorialesIdField;
            }
            set {
                if ((this.EditorialesIdField.Equals(value) != true)) {
                    this.EditorialesIdField = value;
                    this.RaisePropertyChanged("EditorialesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((this.ISBNField.Equals(value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Npaginas {
            get {
                return this.NpaginasField;
            }
            set {
                if ((object.ReferenceEquals(this.NpaginasField, value) != true)) {
                    this.NpaginasField = value;
                    this.RaisePropertyChanged("Npaginas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sinopsis {
            get {
                return this.SinopsisField;
            }
            set {
                if ((object.ReferenceEquals(this.SinopsisField, value) != true)) {
                    this.SinopsisField = value;
                    this.RaisePropertyChanged("Sinopsis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOEdiitorialRespuesta", Namespace="http://schemas.datacontract.org/2004/07/Libreria.Entidades.WCF.Editorial")]
    [System.SerializableAttribute()]
    public partial class DTOEdiitorialRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Libreria.FrontEnd.LibreriaService.DTOEditorialCuerpo[] CuerpoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Libreria.FrontEnd.LibreriaService.DTOResultado ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Libreria.FrontEnd.LibreriaService.DTOEditorialCuerpo[] Cuerpo {
            get {
                return this.CuerpoField;
            }
            set {
                if ((object.ReferenceEquals(this.CuerpoField, value) != true)) {
                    this.CuerpoField = value;
                    this.RaisePropertyChanged("Cuerpo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Libreria.FrontEnd.LibreriaService.DTOResultado Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibreriaService.ILibreriaServicio")]
    public interface ILibreriaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibreriaServicio/AgregarEditorial", ReplyAction="http://tempuri.org/ILibreriaServicio/AgregarEditorialResponse")]
        Libreria.FrontEnd.LibreriaService.DTOResultado AgregarEditorial(Libreria.FrontEnd.LibreriaService.DTOEditorialCuerpo Editorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibreriaServicio/AgregarEditorial", ReplyAction="http://tempuri.org/ILibreriaServicio/AgregarEditorialResponse")]
        System.Threading.Tasks.Task<Libreria.FrontEnd.LibreriaService.DTOResultado> AgregarEditorialAsync(Libreria.FrontEnd.LibreriaService.DTOEditorialCuerpo Editorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibreriaServicio/AgregarLibro", ReplyAction="http://tempuri.org/ILibreriaServicio/AgregarLibroResponse")]
        Libreria.FrontEnd.LibreriaService.DTOResultado AgregarLibro(Libreria.FrontEnd.LibreriaService.DTOLibroCuerpo Libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibreriaServicio/AgregarLibro", ReplyAction="http://tempuri.org/ILibreriaServicio/AgregarLibroResponse")]
        System.Threading.Tasks.Task<Libreria.FrontEnd.LibreriaService.DTOResultado> AgregarLibroAsync(Libreria.FrontEnd.LibreriaService.DTOLibroCuerpo Libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibreriaServicio/ObtenerEditorial", ReplyAction="http://tempuri.org/ILibreriaServicio/ObtenerEditorialResponse")]
        Libreria.FrontEnd.LibreriaService.DTOEdiitorialRespuesta ObtenerEditorial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibreriaServicio/ObtenerEditorial", ReplyAction="http://tempuri.org/ILibreriaServicio/ObtenerEditorialResponse")]
        System.Threading.Tasks.Task<Libreria.FrontEnd.LibreriaService.DTOEdiitorialRespuesta> ObtenerEditorialAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibreriaServicioChannel : Libreria.FrontEnd.LibreriaService.ILibreriaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibreriaServicioClient : System.ServiceModel.ClientBase<Libreria.FrontEnd.LibreriaService.ILibreriaServicio>, Libreria.FrontEnd.LibreriaService.ILibreriaServicio {
        
        public LibreriaServicioClient() {
        }
        
        public LibreriaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibreriaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibreriaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibreriaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Libreria.FrontEnd.LibreriaService.DTOResultado AgregarEditorial(Libreria.FrontEnd.LibreriaService.DTOEditorialCuerpo Editorial) {
            return base.Channel.AgregarEditorial(Editorial);
        }
        
        public System.Threading.Tasks.Task<Libreria.FrontEnd.LibreriaService.DTOResultado> AgregarEditorialAsync(Libreria.FrontEnd.LibreriaService.DTOEditorialCuerpo Editorial) {
            return base.Channel.AgregarEditorialAsync(Editorial);
        }
        
        public Libreria.FrontEnd.LibreriaService.DTOResultado AgregarLibro(Libreria.FrontEnd.LibreriaService.DTOLibroCuerpo Libro) {
            return base.Channel.AgregarLibro(Libro);
        }
        
        public System.Threading.Tasks.Task<Libreria.FrontEnd.LibreriaService.DTOResultado> AgregarLibroAsync(Libreria.FrontEnd.LibreriaService.DTOLibroCuerpo Libro) {
            return base.Channel.AgregarLibroAsync(Libro);
        }
        
        public Libreria.FrontEnd.LibreriaService.DTOEdiitorialRespuesta ObtenerEditorial() {
            return base.Channel.ObtenerEditorial();
        }
        
        public System.Threading.Tasks.Task<Libreria.FrontEnd.LibreriaService.DTOEdiitorialRespuesta> ObtenerEditorialAsync() {
            return base.Channel.ObtenerEditorialAsync();
        }
    }
}
